language: java

script: ./.travis-build.sh

after_success:
  - curl -LO https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh
  - sh trigger-travis.sh typetools annotation-tools $TRAVISTOKEN "Triggered by upstream build of typetools/jsr308-langtools"

sudo: false

jdk:
  - oraclejdk8
#  - oraclejdk7
  - openjdk7
