language: java

script: ./.travis-build.sh

sudo: false

jdk:
  - oraclejdk8

after_success:
  - |
      if [[ ($TRAVIS_BRANCH == master) &&
            ($TRAVIS_PULL_REQUEST == false) &&
            ( (! $TRAVIS_JOB_NUMBER == *.*) || ($TRAVIS_JOB_NUMBER == *.1) ) ]] ; then
        curl -LO https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh
        sh trigger-travis.sh typetools annotation-tools $TRAVISTOKEN
      fi
